/*USER*/
export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";
export const SET_SIGNUP_ERROR = "SET_SIGNUP_ERROR";
export const SET_SIGNUP_SUCCESS = "SET_SIGNUP_SUCCESS";
export const SET_LOG_OUT_SUCCESS = "SET_LOG_OUT_SUCCESS";

/*POSTS*/
export const SET_POSTS = "SET_POSTS";
export const SET_POSTS_LOADING = "SET_POSTS_LOADING";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const SET_CURRENT_POST_SUCCESS = "SET_CURRENT_POST_SUCCESS";
export const SET_POST_ERROR = "SET_POST_ERROR";
export const SET_POST_MESSAGE_SUCCESS = "SET_POST_MESSAGE_SUCCESS";
export const SET_POST_MESSAGE_ERROR = "SET_POST_MESSAGE_ERROR";
export const SET_MERGE_POSTS = "SET_MERGE_POSTS";
export const LIKE_POST_SUCCESS = "LIKE_POST_SUCCESS";
export const SEARCH_POSTS_SUCCESS = "SEARCH_POSTS_SUCCESS";

/*TAGS*/
export const SET_ALL_TAGS = "SET_ALL_TAGS";

/* APP */
export const SHOW_SNACK = "SHOW_SNACK";
export const HIDE_SNACK = "HIDE_SNACK";
